### PR TITLE
test: add Travis CI configuration

### LINKED ISSUE #2: Test CI service
Would this project be interested in a CI service, like [Travis](https://travis-ci.com), to perform automated testing? It would be pretty easy to set up; just adding a `.travis.yml` and enabling the repository on the Travis website. There are other CIs (like CircleCI) available as well.

### PR DESCRIPTION
**Pull request by ayazhafiz**
Closes #2

### CODE REVIEW

**Comment by ArturKovacs** [comment]
Thanks although the test fail on Linux and Windows. The commands that the implementation uses doesn't seem to exist on Linux if I'm not mistaken. Windows is stranger as it succeeds with two tests then times out on the third. What make makes it even stranger is that `remove_all` succeeds but the regular `remove` is the one hanging.

I feel like both of require some changes in the test setup but on Linux it may be needed to improve the implementation itself so that the environment that the test runs on is also supported.

**Comment by ayazhafiz** [comment]
I'll take a look at fixing this later today. It's almost certainly just the Travis environment, which probably doesn't have any desktop environment.

**Comment by ayazhafiz** [comment]
Sorry, doing arbitrary testing to try to get Travis to work. I'll move this to another branch.

**Comment by ArturKovacs** [comment]
No worries. I didn't even think that you could make a private branch but that is a good idea indeed.

**Comment by ArturKovacs** [comment]
I'm closing this as we have Azure tests set up currently.

**Pull request closed without merging**
