### PR TITLE
Build "linux" module on *BSD (any non-macOS unix)

### PR DESCRIPTION
**Pull request by myfreeweb**

### CODE REVIEW

**Comment by ArturKovacs** [comment]
Thanks, that's great!

**Comment by ArturKovacs** [comment]
Bit of a silly question but have you tested if the linux implementation for trash actually works on a *BSD OS? I don't have a BSD at hand right now. If this actually works, I'll publish a new release with the patch number incremented to crates.io

**Comment by myfreeweb** [comment]
`cargo test` passed of course. (I'm on FreeBSD and not running KDE, so it's using `gio`)

**Comment by ArturKovacs** [comment]
Sounds good! Thanks again.

**Comment by ArturKovacs** [comment]
This is now published as part of v1.0.1 on crates.io

**Pull request merged**
